#!/bin/bash
set -eu -o pipefail

files=$(ls ~/Downloads/everybody_codes_e2025_q[0-9][0-9]_p[123].txt)
[[ 1 == $(wc -l <<< "$files")  ]]
[[ $files =~ e2025_q(..)_p(.) ]]
q=${BASH_REMATCH[1]}
p=${BASH_REMATCH[2]}
mv "$files" q"$q"p"$p".in
